strategy:
  matrix:
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
    linux-stable-gcc-8:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
      gcc_variant: gcc-8
    linux-beta:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: beta
    mac-stable:
      imageName: 'macos-10.14'
      rustup_toolchain: stable
pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: recursive
  - bash: |
      set -e
      export RUSTUP_HOME=$HOME/.rustup
      export CARGO_HOME=$HOME/.cargo
      echo ##vso[task.setvariable variable=RUSTUP_HOME]$HOME/.rustup
      echo ##vso[task.setvariable variable=CARGO_HOME]$HOME/.cargo
      curl https://sh.rustup.rs -sSf | sh -s -- -y --profile=minimal --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.prependpath]$HOME/.cargo/bin"
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install Rust on linux/mac
  - script: |
      set RUSTUP_HOME=%USERPROFILE%\.rustup
      set CARGO_HOME=%USERPROFILE%\.cargo
      echo ##vso[task.setvariable variable=RUSTUP_HOME]%USERPROFILE%\.rustup
      echo ##vso[task.setvariable variable=CARGO_HOME]%USERPROFILE%\.cargo
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --profile=minimal --default-toolchain %RUSTUP_TOOLCHAIN%
      echo ##vso[task.setvariable variable=PATH]%PATH%;%USERPROFILE%\.cargo\bin
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install Rust on windows
  - bash: |
      set -e
      rustup default $RUSTUP_TOOLCHAIN
      rustup update $RUSTUP_TOOLCHAIN
      rustc -vV
      rustup component add rustfmt --toolchain $RUSTUP_TOOLCHAIN
      rustfmt --version
    displayName: "Rust post-install"
  - script: |
      curl http://releases.llvm.org/5.0.2/LLVM-5.0.2-win64.exe -o llvm-installer.exe
      7z x llvm-installer.exe -oc:\llvm-binary
      echo ##vso[task.setvariable variable=LIBCLANG_PATH]C:\llvm-binary\bin
      echo ##vso[task.setvariable variable=PATH]%PATH%;C:\llvm-binary\bin
    condition: and(eq( variables['Agent.OS'], 'Windows_NT' ), eq( variables['platform'], 'x64' ))
    displayName: Install llvm on windows 64bit
  - script: |
      curl http://releases.llvm.org/5.0.2/LLVM-5.0.2-win32.exe -o llvm-installer.exe
      7z x llvm-installer.exe -oc:\llvm-binary
      echo ##vso[task.setvariable variable=LIBCLANG_PATH]C:\llvm-binary\bin
      set JAVA_PKG=zulu8.40.0.25-ca-jdk8.0.222-win_i686
      curl https://cdn.azul.com/zulu/bin/%JAVA_PKG%.zip -o java-win_i686.zip
      7z x java-win_i686.zip -oc:\
      echo ##vso[task.setvariable variable=JAVA_HOME]C:\%JAVA_PKG%
      echo ##vso[task.setvariable variable=PATH]c:\%JAVA_PKG%\bin;%PATH%;C:\llvm-binary\bin
    condition: and(eq( variables['Agent.OS'], 'Windows_NT' ), eq( variables['platform'], 'x86' ))
    displayName: Install dependicies on windows 32bit
  - bash: |
      set -e
      if [ "$GCC_VARIANT" == "gcc-8" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq && sudo apt-get install -qq g++-8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi
      gcc --version
      g++ --version
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Install gcc-8 if required
  - bash: |
      set -e
      clang --version
      rustc -vV
      cargo -vV
      cmake --version
      cargo build
      cargo test
      cargo test --release
    displayName: Build and run tests
