[package]
name = "couchbase-lite-core-sys"
version = "0.2.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.43"
bindgen = "0.53.2"
cc = "1.0.53"
env_logger = "0.7"