[package]
name = "couchbase-lite"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couchbase-lite-core-sys = { path = "../couchbase-lite-core-sys" }
serde = { version = "1.0.84", features = ["derive"] }
uuid = { version = "0.7.1", features = ["v4", "serde", "v3"] }
serde_json = "1.0.17"
json5 = "0.2.4"
fallible-streaming-iterator = "0.1.9"
bitflags = "1.0.4"
once_cell = "1.1.0"
log = "0.4.1"

[dev-dependencies]
tempfile = "3.0"
env_logger = "0.6"