[package]
name = "couchbase-lite"
version = "0.3.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

[features]
default = ["replication", "tls"]
replication = ["tokio-tungstenite", "http", "tokio", "futures-util",  "tokio-native-tls"]
tls = ["tokio-tungstenite/tls"]

[dependencies]
couchbase-lite-core-sys = "0.2.2"
serde = { version = "1.0.104", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4", "serde", "v3"] }
serde_json = "1.0.44"
json5 = "0.2.5"
fallible-streaming-iterator = "0.1.9"
bitflags = "1.2.1"
once_cell = "1.2.0"
log = "0.4.8"
tokio-tungstenite = { version = "0.11.0", optional = true }
http = { version = "0.2.1", optional = true }
tokio = { version = "0.2", default-features = false, features = ["sync", "macros"], optional = true }
futures-util = { version = "0.3.5", optional = true }
tokio-native-tls = { version = "0.1", optional = true }

[dev-dependencies]
tempfile = "3.0"
env_logger = "0.7"
