[package]
name = "chat-demo"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couchbase-lite = { path = "../couchbase-lite" }
serde = { version = "1.0.84", features = ["derive"] }
futures = "0.1.25"
tokio = "0.1.14"
tokio-codec = "0.1.1"
log = "0.4.8"
env_logger = "0.6"